// Code generated by cmd/cgo; DO NOT EDIT.

//line testcgo.go:1:1
package main

// #include "hello.h"
import _ "unsafe"

func main() {
	( /*line :7:2*/_Cfunc_SayHello /*line :7:11*/)(( /*line :7:13*/_Cfunc_CString /*line :7:21*/)("Hello, World\n"))
}
